version: 0.2  # 0.2 권장

phases:   # 빌드 단계
  install:
    runtime-versions:
      java: corretto17
      commands:
        - JAVA_HOME ="/usr/lib/jvm/java-17-amazon-corretto.x86_64"
        - JRE_HOME=${JAVA_HOME}
        - JDK_HOME=${JAVA_HOME}
  pre_build:
    commands:
      - echo Pre-Build completed on `date`
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on $DATE
artifacts:
  files:
    - target/spring-boot-jsp-0.0.1-SNAPSHOT.war  # 업로드 할 파일들
  discard-paths: yes # 파일명 기준으로만 업로드
cache:
  paths:
    - '/root/.m2/**/*'   # S3 cache에 등록할 파일들